# -*- coding: utf-8 -*-
"""魔数签名表 + 扩展名知识库"""

# (类型名, 典型扩展名, 魔数, 分类)
SIGNATURES = [
    ("ZIP",      "zip",   b"PK\x03\x04",                  "压缩包"),
    ("RAR",      "rar",   b"Rar!\x1a\x07",                "压缩包"),
    ("7Z",       "7z",    b"7z\xbc\xaf\x27\x1c",          "压缩包"),
    ("GZIP",     "gz",    b"\x1f\x8b\x08",                "压缩包"),
    ("BZIP2",    "bz2",   b"BZh",                         "压缩包"),
    ("XZ",       "xz",    b"\xfd7zXZ\x00",                "压缩包"),
    ("ZSTD",     "zst",   b"\x28\xb5\x2f\xfd",            "压缩包"),
    ("LZ4",      "lz4",   b"\x04\x22\x4d\x18",            "压缩包"),
    ("CAB",      "cab",   b"MSCF",                        "压缩包"),
    ("WIM",      "wim",   b"MSWIM\x00\x00\x00",           "压缩包"),
    ("PNG",      "png",   b"\x89PNG\r\n\x1a\n",           "图片"),
    ("GIF87a",   "gif",   b"GIF87a",                      "图片"),
    ("GIF89a",   "gif",   b"GIF89a",                      "图片"),
    ("JPEG",     "jpg",   b"\xff\xd8\xff",                "图片"),
    ("RIFF",     "riff",  b"RIFF",                        "多媒体"),
    ("MP4",      "mp4",   b"ftyp",                        "多媒体"),
    ("EBML",     "mkv",   b"\x1a\x45\xdf\xa3",            "多媒体"),
    ("FLV",      "flv",   b"FLV",                         "多媒体"),
    ("ID3",      "mp3",   b"ID3",                         "音频"),
    ("FLAC",     "flac",  b"fLaC",                        "音频"),
    ("OGG",      "ogg",   b"OggS",                        "音频"),
    ("PDF",      "pdf",   b"%PDF",                        "文档"),
    ("EXE",      "exe",   b"MZ",                          "可执行"),
    ("ELF",      "elf",   b"\x7fELF",                     "可执行"),
    ("OLE",      "doc",   b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1", "文档"),
    ("LNK",      "lnk",   b"\x4c\x00\x00\x00\x01\x14\x02\x00", "快捷方式"),
    ("TORRENT",  "torrent", b"d8:announce",               "网络"),
    ("SQLITE",   "db",    b"SQLite format 3\x00",         "数据库"),
    ("ICO",      "ico",   b"\x00\x00\x01\x00",            "图标"),
    ("YPF",      "ypf",   b"YPF\x00",                     "游戏资源"),
    ("YPF1A",    "ypf",   b"YPF\x1a",                     "游戏资源"),
    ("TTC",      "ttc",   b"ttcf",                        "字体"),
    ("TTF",      "ttf",   b"\x00\x01\x00\x00",            "字体"),
    ("OTTO",     "otf",   b"OTTO",                        "字体"),
    ("WOFF",     "woff",  b"wOFF",                        "字体"),
    ("WOFF2",    "woff2", b"wOF2",                        "字体"),
    ("TIFF",     "tif",   b"II*\x00",                     "图片"),
    ("TIFF2",    "tif",   b"MM\x00*",                     "图片"),
    ("PSD",      "psd",   b"8BPS",                        "图片"),
    ("ASF",      "wmv",   b"\x30\x26\xb2\x75\x8e\x66\xcf\x11\xa6\xd9\x00\xaa\x00\x62\xce\x6c", "多媒体"),
    ("RM",       "rm",    b".RMF",                        "多媒体"),
    ("SWF",      "swf",   b"FWS",                         "多媒体"),
    ("SWF2",     "swf",   b"CWS",                         "多媒体"),
    ("SWF3",     "swf",   b"ZWS",                         "多媒体"),
    ("AMR",      "amr",   b"#!AMR",                       "音频"),
    ("APE",      "ape",   b"MAC ",                        "音频"),
    ("MIDI",     "mid",   b"MThd",                        "音频"),
    ("RTF",      "rtf",   b"{\\rtf",                      "文档"),
    ("PEM",      "pem",   b"-----BEGIN",                  "证书"),
    ("JAVA",     "class", b"\xca\xfe\xba\xbe",            "可执行"),
    ("MACHO",    "macho", b"\xcf\xfa\xed\xfe",            "可执行"),
    ("MACHO2",   "macho", b"\xce\xfa\xed\xfe",            "可执行"),
    ("WASM",     "wasm",  b"\x00asm",                     "可执行"),
    ("CRX",      "crx",   b"Cr24",                        "可执行"),
    ("AR",       "deb",   b"!<arch>\n",                   "压缩包"),
    ("RPM",      "rpm",   b"\xed\xab\xee\xdb",            "压缩包"),
    ("XAR",      "xar",   b"xar!",                        "压缩包"),
    ("PCAP",     "pcap",  b"\xd4\xc3\xb2\xa1",            "网络"),
    ("PCAPNG",   "pcapng", b"\x0a\x0d\x0d\x0a",           "网络"),
    ("QCOW",     "qcow2", b"QFI\xfb",                     "磁盘镜像"),
    ("VHD",      "vhd",   b"conectix",                    "磁盘镜像"),
    ("VHDX",     "vhdx",  b"vhdxfile",                    "磁盘镜像"),
    ("VMDK",     "vmdk",  b"KDMV",                        "磁盘镜像"),
    ("VDI",      "vdi",   b"<<< Or",                      "磁盘镜像"),
    ("PARQUET",  "parquet", b"PAR1",                      "数据库"),
]

# 各基础类型对应的合理扩展名（用于"扩展名与内容不符"检测）
TYPE_EXTS = {
    "ZIP": {"zip", "docx", "xlsx", "pptx", "apk", "jar", "epub", "whl", "xapk"},
    "RAR": {"rar"}, "7Z": {"7z"}, "GZIP": {"gz", "tgz"}, "BZIP2": {"bz2"},
    "XZ": {"xz"}, "ZSTD": {"zst"}, "LZ4": {"lz4"}, "CAB": {"cab"}, "WIM": {"wim"},
    "PNG": {"png", "apng"}, "GIF87a": {"gif"}, "GIF89a": {"gif"},
    "JPEG": {"jpg", "jpeg", "jpe"}, "MP4": {"mp4", "m4v", "m4a", "mov", "heic"},
    "RIFF": {"avi", "wav", "webp", "ani", "aiff"},
    "EBML": {"mkv", "webm", "mka"}, "FLV": {"flv"}, "ID3": {"mp3"},
    "FLAC": {"flac"}, "OGG": {"ogg", "opus"}, "PDF": {"pdf"}, "EXE": {"exe", "dll", "scr"},
    "ELF": {"so", "elf", "axf"}, "OLE": {"doc", "xls", "ppt", "msi", "docm"},
    "LNK": {"lnk"}, "TORRENT": {"torrent"}, "SQLITE": {"db", "sqlite", "db3"},
    "ICO": {"ico"}, "YPF": {"ypf"}, "YPF1A": {"ypf"},
    "TTC": {"ttc"}, "TTF": {"ttf"}, "OTTO": {"otf"}, "WOFF": {"woff"}, "WOFF2": {"woff2"},
    "TIFF": {"tif", "tiff"}, "PSD": {"psd"}, "ASF": {"wmv", "wma", "asf"}, "RM": {"rm", "rmvb"},
    "SWF": {"swf"}, "AMR": {"amr"}, "APE": {"ape"}, "MIDI": {"mid", "midi"}, "RTF": {"rtf"},
    "PEM": {"pem", "crt", "key"}, "JAVA": {"class"}, "MACHO": set(), "WASM": {"wasm"},
    "CRX": {"crx"}, "AR": {"deb", "a"}, "RPM": {"rpm"}, "XAR": {"xar"},
    "PCAP": {"pcap"}, "PCAPNG": {"pcapng"}, "QCOW": {"qcow2"}, "VHD": {"vhd"},
    "VHDX": {"vhdx"}, "VMDK": {"vmdk"}, "VDI": {"vdi"}, "PARQUET": {"parquet"},
    # 展示名首词别名（findings[0]["type"] 的首词）
    "WAV": {"wav"}, "AVI": {"avi"}, "WebP": {"webp"}, "GIF": {"gif"},
    "ISO": {"iso"}, "DOCX": {"docx"}, "XLSX": {"xlsx"}, "PPTX": {"pptx"},
    "EPUB": {"epub"}, "APK": {"apk", "xapk"}, "ANI": {"ani"},
    "HEIC": {"heic"}, "HEIF": {"heif", "heic"}, "AVIF": {"avif"}, "MOV": {"mov"},
    "M4A": {"m4a"}, "M4B": {"m4b"}, "3GP": {"3gp"}, "TAR": {"tar"},
}
EXEC_EXTS = (".exe", ".scr", ".bat", ".cmd", ".js", ".vbs", ".ps1", ".com", ".pif", ".msi")
ALL_KNOWN_EXTS = set()
for _v in TYPE_EXTS.values():
    ALL_KNOWN_EXTS |= _v
